### PR TITLE
Add Brazilian Portuguese localization

### PR DESCRIPTION
**Pull request by AluisioASG**
Still pending:
- [x] Restock+ RCS descriptions
- [x] Restock+ lights (need to find in-game)
- [x] Review Restock variant names

I'll get around to those in a day or two.

### CODE REVIEW

**Comment by ChrisAdderley** [comment]
Thanks - ping us when you're set.

**Comment by AluisioASG** [comment]
@ChrisAdderley this is ready. Not quite happy with some of the translations, but I lack the specific vocabulary to make them better, and they're good enough for now.

**Comment by ChrisAdderley** [comment]
Sorry, one more thing - can you add yourself to the localization credits?

**Comment by AluisioASG** [comment]
Sure, done.

**Pull request merged**
