### PR TITLE
v1.4.4 Release PR

### PR DESCRIPTION
**Pull request by Poodmund**
The only outstanding issue I foresee could be fixed prior to the next build release could be https://github.com/PorktoberRevolution/ReStocked/issues/997 but there is a fair bit of transform repositioning to fix the issue.

Would there be anything else that anyone would like to include before the next build?

### CODE REVIEW

**Review by drewcassidy — APPROVED** [review]
lgtm

**Comment by Poodmund** [comment]
I see that the automated build is bundling MM 4.2.1 rather than the current 4.2.2.

Also the .version files in RS and RS+ need updating to v1.4.4 just prior to merging.

**Comment by Poodmund** [comment]
Opened PR with MM 4.4.2 updates to build config files. Ready to be merged once MM 4.4.2 is confirmed to be available on distribution platform to be included.

https://github.com/PorktoberRevolution/ReStocked/pull/999

**Review by drewcassidy — APPROVED** [review]

**Comment by Poodmund** [comment]
Unfortunately, I think Nertea has to give us merge authorisation for the prod branch before we can proceed with this, @drewcassidy.

I have spoken to him last week about this and other bits of the build process but he is understandably very busy right now. 😄

**Comment by Poodmund** [comment]
Not sure why this is failing now in https://github.com/PorktoberRevolution/ReStocked/pull/998/commits/1877cec291a1a1b27f0ecbdff0ad38e56d5bf7e6 compared to https://github.com/PorktoberRevolution/ReStocked/pull/998/commits/c6cf16233e3a86167af671dc87af863405a9f1ba. Seems to be linked to https://github.com/post-kerbin-mining-corporation/build-deploy/blob/master/src/ksp_deploy/helpers.py#L26

**Comment by drewcassidy** [comment]
It was complaining in the past about a deprecation in the python library, and I guess Nert never pinned the version so eventually it used one where it needs `loader`

**Comment by ChrisAdderley** [comment]
I resolved the issue with the package

**Comment by Poodmund** [comment]
> I resolved the issue with the package

It also seems that the external MM reference worked to download and bundle with the package:

```
Run python build-deploy/src/package.py --f "Distribution/Restock/.mod_data.yml"
2024-05-18 18:37:41,915 - packager - INFO - Building ReStock version 1.4.4
=================
2024-05-18 18:37:41,915 - packager - INFO - Compiling core mod content
2024-05-18 18:37:42,711 - packager - INFO - Packaging EXTRAS release packages at Distribution/RestockExtras/
2024-05-18 18:37:42,711 - packager.packaging - INFO - Packaging Extra RestockRigidLegs
2024-05-18 18:37:42,712 - packager - INFO - Packaging complete release package
2024-05-18 18:37:42,712 - packager - INFO - Collecting dependencies
2024-05-18 18:37:42,713 - packager.dependencies - INFO - Collecting ModuleManager at from https://ksp.sarbian.com/jenkins/job/ModuleManager/163/artifact/ModuleManager.4.2.3.dll
2024-05-18 18:37:42,713 - packager.dependencies - INFO - Downloading https://ksp.sarbian.com/jenkins/job/ModuleManager/163/artifact/ModuleManager.4.2.3.dll to tmp/ModuleManager.4.2.3.dll
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connectionpool.py:[10](https://github.com/PorktoberRevolution/ReStocked/actions/runs/9117825663/job/25136842027?pr=998#step:6:11)61: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ksp.sarbian.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2024-05-18 18:37:43,422 - packager - INFO - Packaging COMPLETE release package
2024-05-18 18:38:07,810 - packager.packaging - INFO - Packaged build/ReStock
No .deploy_config.yml file was found, defaults will be used
```
So that's good news. Thank you for fixing the above python library issue. If there are no further issues for this release, could drewcassidy and I get merging authorisation so that we can push releases going forward, please?

image

**Pull request merged**
