### PR TITLE
Change RS+ Science part anim. strings to #LOC tags and resolve stock Satellite contract issue

### PR DESCRIPTION
**Pull request by Poodmund**
I presume that the contract config is fine but someone with a little MM knowledge may be useful just to verify.

### CODE REVIEW

**Comment by drewcassidy** [comment]
This looks like it is replacing the required part, not appending to it

I’m not in a position to test right now but there’s a way to generate contracts in the debut menu that could help to verify this is working

**Comment by Poodmund** [comment]
Untitled-1

Untitled-2

Its a suprising pain in the ass to get the required contracts to generate 😄 	Anyway, seems as though its working just as intended so I'll merge.

**Comment by blowfishpro** [comment]
I have same concern, it appears to be replacing the part in the contracts, not appending.  Everything else seems good though.

Is there even a way to have multiple parts be able to satisfy those satellite contract requirements?  I'm not super familiar with the contract system but based on the structure of the file it seems to me like there may not be

**Comment by blowfishpro** [comment]
I'm still confused as to how this works.  If it's replacing the original parts in those requirements, how do they still work?

**Comment by Poodmund** [comment]
This is the config node in question:

```
PART_REQUEST // A potential mystery goo request for satellites
{
	Article = a // Article (A/An) to be used prior to part description
	PartDescription = #autoLOC_500052 //#autoLOC_500052 = mystery goo unit
	VesselDescription = #autoLOC_500053 //#autoLOC_500053 = satellite
	Keyword = #autoLOC_500054 //#autoLOC_500054 = Scientific
	Part = GooExperiment // A part ID that triggers this request
	MinimumScience = 7 // A minimum value this request places on science rewards
	Trivial // Easy Contracts
	{
		Weight = 5 // How common this request is in easy contracts
		FundsMultiplier = 1.05 // The multiplier this request places on funds in easy contracts
		ScienceMultiplier = 1.25 // The multiplier this request places on science in easy contracts
		ReputationMultiplier = 1.05 // The multiplier this request places on reputation in easy contracts
	}
	Significant // Medium Contracts
	{
		Weight = 15 // How common this request is in medium contracts
		FundsMultiplier = 1.05 // The multiplier this request places on funds in medium contracts
		ScienceMultiplier = 1.25 // The multiplier this request places on science in medium contracts
		ReputationMultiplier = 1.05 // The multiplier this request places on reputation in medium contracts
	}
	Exceptional // Hard Contracts
	{
		Weight = 25 // How common this request is in hard contracts
		FundsMultiplier = 1.05 // The multiplier this request places on funds in hard contracts
		ScienceMultiplier = 1.25 // The multiplier this request places on science in hard contracts
		ReputationMultiplier = 1.05 // The multiplier this request places on reputation in hard contracts
	}
}
```
All the new config is doing is **adding** another line:
```
Part = restock-goocanister-625-1
```
So that is exists alongside the current line:
```
Part = GooExperiment
```
So it seems the contracts can have multiple listed parts to satisfy their criteria.

**Pull request merged**
